import type { Metadata } from "next";
import { ibm_Plex_Sans } from "./ui/fonts";
import "./globals.css";
import { Providers } from "./providers";
import Nav from "@/app/ui/components/Navbar";
import Footer from "@/app/ui/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={`${ibm_Plex_Sans.className} antialiased`}>
        <Providers>
          <Nav />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
